################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
code/lv_lib_100ask/src/lv_100ask_2048 \
code/lv_lib_100ask/src/lv_100ask_calc \
code/lv_lib_100ask/src/lv_100ask_file_explorer \
code/lv_lib_100ask/src/lv_100ask_memory_game \
code/lv_lib_100ask/src/lv_100ask_page_manager \
code/lv_lib_100ask/src/lv_100ask_pinyin_ime \
code/lv_lib_100ask/src/lv_100ask_sketchpad \
code/lv_lib_100ask/test/lv_100ask_2048_test \
code/lv_lib_100ask/test/lv_100ask_calc_test \
code/lv_lib_100ask/test/lv_100ask_file_explorer \
code/lv_lib_100ask/test/lv_100ask_memory_game_test \
code/lv_lib_100ask/test/lv_100ask_nes_test \
code/lv_lib_100ask/test/lv_100ask_page_manager_test \
code/lv_lib_100ask/test/lv_100ask_pinyin_ime_test \
code/lv_lib_100ask/test/lv_100ask_sketchpad_test \
code/lvgl/porting \
code/lvgl/src/core \
code/lvgl/src/draw/arm2d \
code/lvgl/src/draw \
code/lvgl/src/draw/nxp/pxp \
code/lvgl/src/draw/nxp/vglite \
code/lvgl/src/draw/renesas \
code/lvgl/src/draw/sdl \
code/lvgl/src/draw/stm32_dma2d \
code/lvgl/src/draw/sw \
code/lvgl/src/draw/swm341_dma2d \
code/lvgl/src/extra/layouts/flex \
code/lvgl/src/extra/layouts/grid \
code/lvgl/src/extra/libs/bmp \
code/lvgl/src/extra/libs/ffmpeg \
code/lvgl/src/extra/libs/freetype \
code/lvgl/src/extra/libs/fsdrv \
code/lvgl/src/extra/libs/gif \
code/lvgl/src/extra/libs/png \
code/lvgl/src/extra/libs/qrcode \
code/lvgl/src/extra/libs/rlottie \
code/lvgl/src/extra/libs/sjpg \
code/lvgl/src/extra/libs/tiny_ttf \
code/lvgl/src/extra \
code/lvgl/src/extra/others/fragment \
code/lvgl/src/extra/others/gridnav \
code/lvgl/src/extra/others/ime \
code/lvgl/src/extra/others/imgfont \
code/lvgl/src/extra/others/monkey \
code/lvgl/src/extra/others/msg \
code/lvgl/src/extra/others/snapshot \
code/lvgl/src/extra/themes/basic \
code/lvgl/src/extra/themes/default \
code/lvgl/src/extra/themes/mono \
code/lvgl/src/extra/widgets/animimg \
code/lvgl/src/extra/widgets/calendar \
code/lvgl/src/extra/widgets/chart \
code/lvgl/src/extra/widgets/colorwheel \
code/lvgl/src/extra/widgets/imgbtn \
code/lvgl/src/extra/widgets/keyboard \
code/lvgl/src/extra/widgets/led \
code/lvgl/src/extra/widgets/list \
code/lvgl/src/extra/widgets/menu \
code/lvgl/src/extra/widgets/meter \
code/lvgl/src/extra/widgets/msgbox \
code/lvgl/src/extra/widgets/span \
code/lvgl/src/extra/widgets/spinbox \
code/lvgl/src/extra/widgets/spinner \
code/lvgl/src/extra/widgets/tabview \
code/lvgl/src/extra/widgets/tileview \
code/lvgl/src/extra/widgets/win \
code/lvgl/src/font \
code/lvgl/src/hal \
code/lvgl/src/misc \
code/lvgl/src/widgets \
code \
code/ui/src \
libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
libraries/infineon_libraries/Service/CpuGeneric/If \
libraries/infineon_libraries/Service/CpuGeneric/StdIf \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Asc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/CStart \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Irq \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Dma \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Flash/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Mtu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Scu/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Src/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Adc \
libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Std \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_Impl \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
libraries/infineon_libraries/iLLD/TC26B/Tricore/_PinMap \
libraries/zf_common \
libraries/zf_components \
libraries/zf_device \
libraries/zf_driver \
user \

