// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "all_data.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label11;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label12;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label13;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label14;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label1, "%d", roll.cnt);    
        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[0],roll.y[0],roll.cnt);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label2, "%d", roll.cnt);
        _ui_state_modify(ui_Button2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[1],roll.y[1],roll.cnt);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label3, "%d", roll.cnt);
        _ui_state_modify(ui_Button3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[2],roll.y[2],roll.cnt);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label4, "%d", roll.cnt);
        _ui_state_modify(ui_Button4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[3],roll.y[3],roll.cnt);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label5, "%d", roll.cnt);
        _ui_state_modify(ui_Button5, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[4],roll.y[4],roll.cnt);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label6, "%d", roll.cnt);
        _ui_state_modify(ui_Button6, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[5],roll.y[5],roll.cnt);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label7, "%d", roll.cnt);
        _ui_state_modify(ui_Button7, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[6],roll.y[6],roll.cnt);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label8, "%d", roll.cnt);
        _ui_state_modify(ui_Button8, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[7],roll.y[7],roll.cnt);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label9, "%d", roll.cnt);
        _ui_state_modify(ui_Button9, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[8],roll.y[8],roll.cnt);
    }
}
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label10, "%d", roll.cnt);
        //_ui_state_modify(ui_Button10, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[9],roll.y[9],roll.cnt);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label11, "%d", roll.cnt);
        //_ui_state_modify(ui_Button11, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[10],roll.y[10],roll.cnt);
    }
}
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label12, "%d", roll.cnt);
       // _ui_state_modify(ui_Button12, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[11],roll.y[11],roll.cnt);
    }
}
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        roll.cnt++;lv_label_set_text_fmt(ui_Label13, "%d", roll.cnt);
       // _ui_state_modify(ui_Button13, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        printf("[lv_m=%d lv_n=%d lv_k=%d*]",roll.x[12],roll.y[12],roll.cnt);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        roll.cnt=0;
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);

        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button3, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button4, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button5, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);    
        _ui_state_modify(ui_Button6, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button7, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button8, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button9, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button10, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button11, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button12, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button13, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);

        lv_label_set_text_fmt(ui_Label1, "%d", 1);
        lv_label_set_text_fmt(ui_Label2, "%d", 2);
        lv_label_set_text_fmt(ui_Label3, "%d", 3);
        lv_label_set_text_fmt(ui_Label4, "%d", 4);
        lv_label_set_text_fmt(ui_Label5, "%d", 5);
        lv_label_set_text_fmt(ui_Label6, "%d", 6);
        lv_label_set_text_fmt(ui_Label7, "%d", 7);  
        lv_label_set_text_fmt(ui_Label8, "%d", 8);
        lv_label_set_text_fmt(ui_Label9, "%d", 9);
        lv_label_set_text_fmt(ui_Label10, "%d", 10);
        lv_label_set_text_fmt(ui_Label11, "%d", 11);
        lv_label_set_text_fmt(ui_Label12, "%d", 12);
        lv_label_set_text_fmt(ui_Label13, "%d", 13);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
